spring:
  main:
    banner-mode: off
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://shwan.be:5432/dart
    username: shwan
    password: tmdghks24
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

---
spring:
  profiles:
    active: local
---
spring:
  profiles:
    active: real